"""
Generates a complete, buildable ROS 2 package directory containing:
  urdf/, meshes/visual/, meshes/collision/, launch/, config/, worlds/
with package.xml, CMakeLists.txt, and launch files.
"""
import os
import re
import shutil
from typing import List
from utils.logger import get_logger


def _safe_pkg_name(name: str) -> str:
    """ROS 2 package names: lowercase letters, digits, underscores only."""
    safe = re.sub(r'[^a-z0-9_]', '_', name.lower())
    safe = re.sub(r'_+', '_', safe).strip('_')
    return safe or 'robot'

log = get_logger(__name__)


class ROSPackageBuilder:

    def build(self,
              package_name: str,
              output_dir: str,
              urdf_path: str,
              visual_meshes: List[str],
              collision_meshes: List[str]) -> str:
        """
        Assemble the complete ROS 2 package.
        Returns the path to the created package directory.
        """
        package_name = _safe_pkg_name(package_name)
        pkg_dir = os.path.join(output_dir, package_name)

        for sub in ['urdf', 'meshes/visual', 'meshes/collision',
                    'launch', 'config', 'worlds']:
            os.makedirs(os.path.join(pkg_dir, sub), exist_ok=True)

        shutil.copy(urdf_path,
                    os.path.join(pkg_dir, 'urdf', f'{package_name}.urdf'))

        for m in visual_meshes:
            shutil.copy(m, os.path.join(pkg_dir, 'meshes', 'visual',
                                        os.path.basename(m)))
        for m in collision_meshes:
            shutil.copy(m, os.path.join(pkg_dir, 'meshes', 'collision',
                                        os.path.basename(m)))

        self._write_package_xml(pkg_dir, package_name)
        self._write_cmakelists(pkg_dir, package_name)
        self._write_display_launch(pkg_dir, package_name)
        self._write_gazebo_launch(pkg_dir, package_name)
        self._write_controllers_yaml(pkg_dir)
        self._write_empty_world(pkg_dir)

        log.info(f"ROS 2 package built: {pkg_dir}")
        return pkg_dir

    # ------------------------------------------------------------------
    # File writers
    # ------------------------------------------------------------------

    def _write_package_xml(self, pkg_dir: str, name: str):
        content = f"""<?xml version="1.0"?>
<package format="3">
  <name>{name}</name>
  <version>0.0.1</version>
  <description>Auto-generated by CAD2URDF</description>
  <maintainer email="user@email.com">User</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""
        with open(os.path.join(pkg_dir, 'package.xml'), 'w') as f:
            f.write(content)

    def _write_cmakelists(self, pkg_dir: str, name: str):
        content = f"""cmake_minimum_required(VERSION 3.8)
project({name})

find_package(ament_cmake REQUIRED)

install(DIRECTORY
  urdf
  meshes
  launch
  config
  worlds
  DESTINATION share/${{PROJECT_NAME}}
)

ament_package()
"""
        with open(os.path.join(pkg_dir, 'CMakeLists.txt'), 'w') as f:
            f.write(content)

    def _write_display_launch(self, pkg_dir: str, name: str):
        content = f'''from launch import LaunchDescription
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():
    pkg = get_package_share_directory("{name}")
    urdf_path = os.path.join(pkg, "urdf", "{name}.urdf")

    with open(urdf_path, "r") as f:
        robot_description = f.read()

    return LaunchDescription([
        Node(
            package="robot_state_publisher",
            executable="robot_state_publisher",
            name="robot_state_publisher",
            parameters=[{{"robot_description": robot_description}}],
        ),
        Node(
            package="joint_state_publisher_gui",
            executable="joint_state_publisher_gui",
            name="joint_state_publisher_gui",
        ),
        Node(
            package="rviz2",
            executable="rviz2",
            name="rviz2",
        ),
    ])
'''
        with open(os.path.join(pkg_dir, 'launch', 'display.launch.py'), 'w') as f:
            f.write(content)

    def _write_gazebo_launch(self, pkg_dir: str, name: str):
        content = f'''from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, ExecuteProcess
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():
    pkg = get_package_share_directory("{name}")
    urdf_path = os.path.join(pkg, "urdf", "{name}.urdf")

    with open(urdf_path, "r") as f:
        robot_description = f.read()

    return LaunchDescription([
        ExecuteProcess(
            cmd=["gazebo", "--verbose", "-s", "libgazebo_ros_factory.so"],
            output="screen",
        ),
        Node(
            package="robot_state_publisher",
            executable="robot_state_publisher",
            parameters=[{{"robot_description": robot_description}}],
        ),
        Node(
            package="gazebo_ros",
            executable="spawn_entity.py",
            arguments=["-topic", "robot_description", "-entity", "{name}"],
            output="screen",
        ),
    ])
'''
        with open(os.path.join(pkg_dir, 'launch', 'gazebo.launch.py'), 'w') as f:
            f.write(content)

    def _write_controllers_yaml(self, pkg_dir: str):
        content = """controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints: []
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
"""
        with open(os.path.join(pkg_dir, 'config', 'controllers.yaml'), 'w') as f:
            f.write(content)

    def _write_empty_world(self, pkg_dir: str):
        content = """<?xml version="1.0"?>
<sdf version="1.6">
  <world name="default">
    <include>
      <uri>model://ground_plane</uri>
    </include>
    <include>
      <uri>model://sun</uri>
    </include>
    <gravity>0 0 -9.81</gravity>
    <physics type="ode">
      <real_time_update_rate>1000</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
    </physics>
  </world>
</sdf>
"""
        with open(os.path.join(pkg_dir, 'worlds', 'empty.world'), 'w') as f:
            f.write(content)
